## 模块
一组特定功能的类，函数的打包

模块内的`__init__.py` 在python3.3之后的版本非必须，但仍建议加上。当导入一个包时，会自动执行`__init__.py`中的代码，例如，在django项目中使用pymysql模块时需要在配置文件所在包的`__init__.py`中添加如下语句：

```python
import pymysql
pymysql.install_as_MySQLdb() 
```
### 导入模块后发生了什么？
#### 第一次导入时
- 在自己当下的命名空间中，执行所有的代码
- 创建一个模块对象，并将模块内所有的顶级变量买个属性的形式绑定到模块对象上
- 在import的位置，引入import后面的变量名称到当前 命名空间

**从哪个位置导入**
- 内置模块
- sys.path
    - 当前 目录
    - 环境变量
    - 安装路径的lib库
- 追加路径（修改sys.path, 环境变量等，添加.pth文件）

对于.pth文件的优先级，安装路径下的.pth文件>site-package>site-packge路径中的.pth文件
##### 覆盖导入
当自定义的模块与内置模块同名时，我们导入的是内置模块，因为内置模块优先级最高上。
当自定义的模块与与非内置标准模块同名，这种两种情况都可能，两者路径都在sys.path中，谁在前就会导入谁，并覆盖后者。这种情况下，我们可以使用`from my_module import my_func`这种指定从哪个模块导入的方式，如果你写过celery可能会遇到这种情况，在celery中的一种解决方式是`from __future__ import absolute_import`

##### 局部导入
在某个局部范围内导入,因为模块，函数，类等都会产生自己的命名空间，当我们在某个局部才导入模块，那么此模块的生命周期也仅仅在此范围
另一方面，导入模块也会消耗内存，耗时，有些模块只有某种特定情况下才需要，那么只要当那种情况发生时需要导入。
```python
def main():
    import module1
    pass
```

##### 循环导入
循环导入要把握的要点：当遇到import时，会跳转到要导入的文件，然后把该文件内容全部执行一遍，并在导入的地方产生对应的命名空间，绑定导入的模块中的所有对象。这咱遇到import跳转的情况不仅仅发生在第一次导入时，当在要导入的文件中又遇到import时会再次跳转，当完成该次导入后再跳转回来，继续执行剩下的代码。如果已经有该模块的命名空间，则不会重复导入，但会绑定该模块中的还没有绑定的对象。


##### 可选导入
当两个模块api相同，我们想优先导入m1,如果m1导入失败再导入m2时，可以考虑优先导入的方式
```python
try:
    import m1 as m
except ModuleNotFoundError:
    import m2 as m
    
m1.run()
```
我们导入后，将两个模块都取相同的别名，因为api一样，这样我们就可以在导入后使用统一的调用

##### 包内导入
```
├── mod1
│   ├── __init__.py
│   ├── lib1.py
│   └── lib2.py
├── test.py

```
lib1.py
```python
name = 'lib1'
```

lib2.py
```python
from . import lib1

name = 'lib2'
print(lib1.name)
```

test.py
```python
from mod1 import lib1 ,lib2

print(lib1.name)
print(lib2.name)
```

包内导入，在python3中，默认是绝对导入，当我们使用`.`导入时，是按照包的路径来导的，在外部的test.py中导入lib1,lib2，并使用其中的变量。此时无法使用相对导入，但lib1,lib2是在Mod1包内，可以使用相对导入，在lib2中我们使用相对导入，mod1.lib, mod1.lib2, 在lib2中使用相对导入即从“点”查找，即从lib2,找到mod1,而mod1中是能找到lib1的，所以能正常导入，**但是** 如果我们直接运行lib1.py则会报错，因为直接运行的话，当前`__name__ == '__main__'` 而它没有`.`路径，所以无法找到，同样的原理，如果我们想在lib1,或者lib2中导入外层的test同级的文件，则无法导入，因为mod只到了mod1,再上一层没有mod，（不能简单的将相对导入理解为路径的上一层 ）

#### 第二次导入时：
  只执行第一步导入时的第三步

**从哪个位置导入**


### 内置模块
```python
如果一个对象定义了 __set__() 或 __delete__()，则它会被视为数据描述器。 仅定义了 __get__() 的描述器称为非数据描述器（它们经常被用于方法，但也可以有其他用途）

['ArithmeticError', 'AssertionError', 'AttributeError', 'BaseException', 'BlockingIOError', 'BrokenPipeError', 'BufferError', 'BytesWarning', 'ChildProcessError', 'ConnectionAbortedError', 'ConnectionError', 'ConnectionRefusedError', 'ConnectionResetError', 'DeprecationWarning', 'EOFError', 'Ellipsis', 'EnvironmentError', 'Exception', 'False', 'FileExistsError', 'FileNotFoundError', 'FloatingPointError', 'FutureWarning', 'GeneratorExit', 'IOError', 'ImportError', 'ImportWarning', 'IndentationError', 'IndexError', 'InterruptedError', 'IsADirectoryError', 'KeyError', 'KeyboardInterrupt', 'LookupError', 'MemoryError', 'ModuleNotFoundError', 'NameError', 'None', 'NotADirectoryError', 'NotImplemented', 'NotImplementedError', 'OSError', 'OverflowError', 'PendingDeprecationWarning', 'PermissionError', 'ProcessLookupError', 'RecursionError', 'ReferenceError', 'ResourceWarning', 'RuntimeError', 'RuntimeWarning', 'StopAsyncIteration', 'StopIteration', 'SyntaxError', 'SyntaxWarning', 'SystemError', 'SystemExit', 'TabError', 'TimeoutError', 'True', 'TypeError', 'UnboundLocalError', 'UnicodeDecodeError', 'UnicodeEncodeError', 'UnicodeError', 'UnicodeTranslateError', 'UnicodeWarning', 'UserWarning', 'ValueError', 'Warning', 'ZeroDivisionError', '__build_class__', '__debug__', '__doc__', '__import__', '__loader__', '__name__', '__package__', '__spec__', 'abs', 'all', 'any', 'ascii', 'bin', 'bool', 'bytearray', 'bytes', 'callable', 'chr', 'classmethod', 'compile', 'complex', 'copyright', 'credits', 'delattr', 'dict', 'dir', 'divmod', 'enumerate', 'eval', 'exec', 'exit', 'filter', 'float', 'format', 'frozenset', 'getattr', 'globals', 'hasattr', 'hash', 'help', 'hex', 'id', 'input', 'int', 'isinstance', 'issubclass', 'iter', 'len', 'license', 'list', 'locals', 'map', 'max', 'memoryview', 'min', 'next', 'object', 'oct', 'open', 'ord', 'pow', 'print', 'property', 'quit', 'range', 'repr', 'reversed', 'round', 'set', 'setattr', 'slice', 'sorted', 'staticmethod', 'str', 'sum', 'super', 'tuple', 'type', 'vars', 'zip']

```

### pypi发布包

#### 账号操作
注册：https://pypi.python.org/pypi，邮箱验证：https://pypi.org/manage/account

#### 环境准备
setuptools：
https://pypi.python.org 搜索setuptools 下载源码文件，解压，在命令行中切换到setup.py所在目录，执行`python setup.py install `

 pip：
 setuptools安装完后，会有一个安装脚本，执行`easy_install pip`

wheel:
在命令行中执行`pip install wheel` 或者`python3 -m pip install wheel`

 twine:
执行：`pip install twine` 或者 `python3 -m pip install twine`

#### 发布前准备
主要分两步：创建一个项目，编译生成发布包

##### 结构：
![%E5%8F%91%E5%B8%83%E5%8C%85%E9%A1%B9%E7%9B%AE%E7%BB%93%E6%9E%84](vimages/1857012210465.jpg "发布包项目结构")

##### 命名：
不能和已有的冲突
- 全部小写
- 多个单词以中划线分割（不要下划线，pip对下划线支持不友好）


##### setup.py
setup的作用：项目信息的配置文件，里面最重要的是执行一个setup函数，通过这个函数来指明信息
```python
from distutils.core import setup
setup(arg1=args1,arg2=arg2)

from setuptools import setup
setup(arg1=arg1,arg2=arg2)
```
参数说明：
- 名称 *
- 版本 *
- 描述信息 *
- 需要处理的包列表


readMe.rst:
主要是对模块的说明
语法检测：pypi上对rst解析器并不是sphinx导致部分语法有差异，无法正常显示。解决方法是先在本地对long_description 进行验证：
```python
pip install readme_renderer
python3 setup.py check -r -s
```
### tqdm

```python
In [4]: for i in tqdm(range(1000)): 
   ...:     time.sleep(0.001) 
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:01<00:00, 842.38it/s]

```

### socket
wrap_socket 旧的接口不能用，改为使用context

```python
cert_file = str('')
key_file = str('')
context = ssl.SSLContext(ssl.ProTocol_SSLv23)
context.check_hostname = False
context.verify_mode = ssl.CERT_NONE
context.load_cert_chain(cert,key)
_socket = context.wrap_socket()
```

### datetime to timezone
```python
import pytz
from datetime import datetime
unware_time = datetime.strptime(time_str,'%Y-%d-%d %H:%M:%s')
unware_time.replace(tzinfo=pytz.UTC)
```

### re

#### look around:

- look forward

```python

In [12]: txt = "i love python, i love regex"
# 后面是python的Love
In [13]: pattern = re.compile("love\s(?=python)")
# 所以这里只能匹配出第一个love, 因为第二个love后面接的regex
In [14]: pattern.search(txt)
Out[14]: <re.Match object; span=(2, 7), match='love '>
# 后面不是python的Love
In [15]: pattern = re.compile("love\s(?!python)")
# 通过索引可以看到，匹配的是第二个love, 因为第一个Love后面接的是python
In [16]: pattern.search(txt)
Out[16]: <re.Match object; span=(17, 22), match='love '>
# 后面既不能是python也不能是love
In [17]: pattern = re.compile("love\s(?!python|regex)")

In [18]: pattern.search(txt)
```

the word after "?=" or "?!" will not consuming characters. the first one `love\s(?=python)` means only match the word love which is followed by python.
if i change the "?=" to "?!" means not match, so the result is the "love" folled by regex

- look back/behind

```python
# 肯定型后视断言，这里的<= 可以理解为在当前位置回退几个字符，看是否能匹配上内部的模式
# 这里的内部的模式即pattern in the brackets, but remmber the pattern lenght is
# accurate, but not variable(a.*, a{3,4} is not allowed)
In [72]: text = "love regex or hate regex, can't ignore regex"

In [73]: pattern = re.compile("(?<=(love|hate)\s)regex")

In [74]: pattern.findall(text)
Out[74]: ['love', 'hate']

# negetive look back, which is oppoiste to the up one
In [94]: pattern = re.compile("(?<!love\s)regex")

In [95]: pattern.findall(text)
Out[95]: ['regex', 'regex']

# i don't known why this negetive lookbehind not work even if i change the 
# the inside mode to a or anything else.
In [96]: pattern = re.compile("(?<!(love|hate)\s)regex")
In [97]: pattern.findall(text)
Out[97]: ['']

```

the word after ?<= will only match the word  has hate or love before regex.  and ?<! not match. but there is sth confusing: when i use "love|hate" why it return "" ? 


### template

```python
from string import Template

class MyTemplate(Template):
    delemiter = "#"

def main():
    cart = []
    cart.append(dict(item="coke",price=8,qty=2))
    cart.append(dict(item="Cake",price=12,qty=1))
    cart.append(dict(item="Fish",price=32,qty=4))

    t = Template("$qty x $item = $price")
    total =0
    print("cart")
    for data in cart:
        print(t.substitute(data))
        total ++ data["price"]
    print("Total:" + str(total))

if __name__ == "__main__":
    main()

```

### argparse
 argparse example
```python
#!/usr/bin/env python
# coding: utf-8 
# Create by Andy963 @2021-01-10 10:50:27


import argparse


def fib(n):
    a, b = 0, 1
    for i in range(n):
        a, b = b, a + b
    return a


def main():
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group()
    group.add_argument("-v", "--verbose", action="store_true")
    group.add_argument("-q", "--quite", action="store_true")

    parser.add_argument("num", help="The fibonacci number you wish to calculate.", type=int)
    parser.add_argument('-o', "--output", help="Output result to a file", action="store_true")
    args = parser.parse_args()

    result = fib(args.num)
    if args.verbose:
        print("The " + str(args.num) + "th fib number is " + str(result))
    elif args.quite:
        print(result)
    else:
        print("fib(" + str(args.num) + ") =" + str(result))

    if args.output:
        f = open("fib.txt", "a")
        f.write(str(result) + "\n")


if __name__ == '__main__':
    main()
```